RUNNING_STATE = 1

EMPTY_SQUARE = "empty"
FLAG_SQUARE = "flag"
MINE_SQUARE = ""

BACKGROUND_COLOR = (69, 139, 0)

WINDOW_HEIGHT = 750
WINDOW_WIDTH = 1500
SQUARE_HEIGHT = 30

NUM_OF_ROWS = 25
NUM_OF_COLS = 50

BLACK = (0, 0, 0)


SOLDIER_HEIGHT = 4
SOLDIER_WIDTH = 2

GRASS_IMG = "grass.png"
GRASS_HEIGHT = 30
GRASS_WIDTH = 30

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = BLACK
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
